---
- hosts: mlwww
  become: true
  gather_facts: no

  pre_tasks:
    - raw: apt-get install -y python-simplejson

  roles:
    - role: mattiaslundberg.letsencrypt
      letsencrypt_email: "me@mlundberg.se"
      domain_name: "mlundberg.se"

  tasks:
    - name: Upgrade system
      apt: upgrade=dist update_cache=yes
